[package]
name = "chess"
version = "0.1.0"
authors = ["Lucy <lucyperopero@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_enum = "0.5.*"
ansi_term = "0.12.1"
macroquad = "0.3.0-alpha.17"

[features]
default = ["assets"]
assets = []
