name: CI

on:
  push:
    branches:
    - main

    paths:
    - 'chess-rs-server/src/**.rs'

  pull_request:
    branches:
    - main

    paths:
    - 'chess-rs-server/src/**.rs'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Rust toolchain
      run: rustup default stable

    - name: Build
      run: cargo build --bin chess-rs-server --release

    - name: Run tests
      run: cargo test --bin chess-rs-server --verbose

    # - name: Rustfmt and Clippy
    #   run: |
    #     cargo fmt -- --check
    #     cargo clippy

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: chess-rs-server
        path: target/release/chess-rs-server

    - name: Notify server
      run: echo $GITHUB_JOB | netcat ${{secrets.SECRET_SERVER_IP}} 3334

